server {
    listen 8080;

    location / {
        proxy_pass https://project-dockerized-application.onrender.com;
        proxy_set_header Host project-dockerized-application.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
    }
}