services:
  - type: web
    name: project-dockerized-application-blueprint
    runtime: docker
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_DEBUG
        value: "0"

      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres
          property: connectionString

  - type: web
    name: project-dockerized-application-frontend-blueprint
    runtime: docker
    branch: main
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    plan: free

databases:
  - name: todo-postgres
    plan: free
